# Generated by Django 4.2.6 on 2023-12-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='link',
        ),
    ]
